### ISSUE TITLE
Free shipping promo code issue (on mobile)

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#1065]
### Issue Overview:

>[View Slack Thread](https://ifixit.slack.com/archives/C0252FETV2S/p1669239165083709)

>The issue seems to be that the mobile version of Shopify is asking you for the promo code after the shipping method was selected, which is making the cart out of date and and not letting to code apply properly without intentionally hitting the change shipping method button.
>
> **Jackie P.**

---

Navigate to 1:00 to see the price before/after the promotion code is applied

https://user-images.githubusercontent.com/95656772/204074478-222ea3f9-b4cf-456e-8396-f95f873b2897.mp4

From this video, we can see that the shipping rate remains unchanged and the user has to manually go back to the shipping method step in order for the discount code to be properly applied for free shipping.

**Comment by dhmacs** [comment]
@jordycosta I'm not sure if this has anything to do with this repo, since these are all Shopify checkout screens. It looks like the free shipping discount UI isn't playing well with calculated rates. Is this the first time that you're doing free shipping discounts? I'd probably chat with Shopify and ask them about this

> The issue seems to be that the mobile version of Shopify is asking you for the promo code after the shipping method was selected

Not really, if you expand the order summary you can insert the discount:

<img width="445" alt="Screenshot 2022-11-28 at 12 17 28" src="https://user-images.githubusercontent.com/4640135/204264858-4074d023-6e5f-46ba-a5d6-635eddb4ce63.png">

**Comment by jordycosta** [comment]
Re-opened via https://github.com/iFixit/shopify-v2/issues/957
