### ISSUE TITLE
Update our CI infrastructure to support running Playwright tests

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1114]

**Comment by batbattur** [comment]
Found this article very interesting https://kontent.ai/blog/next-js-playwright-tests-github-action/.

They are using the deployed vercel pages to run the e2e tests:
>Now, as I mentioned above, we need to have a built site before we can run the tests. We could, of course, use a GitHub Action to build the site on every PR, but:
> - We’d still need to deploy it somewhere so that Playwright can access it.
> - It would be a waste of resources, as Vercel is already building and hosting the site for us.

>Instead, we’ll just wait for Vercel to build the preview and use it for our tests. We’ll create a GitHub Action that will:
> - Wait for Vercel and grab the preview URL
> - Set up Playwright environment
> - Run the tests

**Comment by ardelato** [comment]
If we use the site built by Vercel, we would be able to inject `MSW` as the server?

**Comment by batbattur** [comment]
> If we use the site built by Vercel, we would be able to inject `MSW` as the server?

I'm not sure how it will work with `MSW`. 

I guess the downside of using the Vercel site is that we have to wait for it to be done (which may take longer than building it in the gh workflow). Also, if something goes wrong with Vercel, the workflow will be useless since we would rely on Vercel to always work. So I think building it in the workflow might be better since we won't depend on external service.

**Comment by ardelato** [comment]
If it is easier and faster to integrate `Playwright` into our CI pipeline by using the `Vercel` site, then we should start with that. Afterward, we can start working on building the site within the workflow. 

Basically, we are also trying to run `Playwright` in parallel with `Cypress` as soon as possible to address any issues sooner than later.
