### ISSUE TITLE
Collection Children: Displaying featured subcollections as child devices

### ISSUE THREAD

**Issue by evannoronha** [iFixit/react-commerce#114]
Problem
---
On the "iPhone X Parts" collection list page, there's a section labelled "Choose a model of iPhone X Parts," but displays components. The inclusion of the word "model" is kind of confusing here.

Background
---
Here, the bug is that we're munging two concepts together: 'device collections' vs 'item-type X device collections'

This is a result of bad data in strapi. We're failing to distinguish a collection whose type is a device collection from a collection whose type is device x item-type.

 
Do This
---
In reality, this type of collection (product x item-type) should be a featured subcollection.
We may need to update the 'parent' relation in strapi such that it also sanely handles the parent- subcollection relation.

CC @sterlinghirsh @lithobraking

**Comment by kwiens** [comment]
I believe this is solved now!
https://react-commerce-ifixit.vercel.app/collections/iphone-x

**Comment by dhmacs** [comment]
@kwiens nothing has been done to solve this, I was waiting an answer to this comment https://github.com/iFixit/react-commerce/issues/114#issuecomment-952576940 in order to decide how to move forward

**Comment by sterlinghirsh** [comment]
I think using the featured subcollection relation is correct. I was thinking about how to handle breadcrumbs and device page linking in those cases, though. "iPhone Batteries" should have a breadcrumb to "iPhone Parts" but not "Phone Parts". That is, link to the collection that we're a subcollection of. We'll need to make sure not to mark "Phone Parts" as the parent page of "iPhone Batteries", even though Phone is the parent device of iPhone, but I think all that will be taken care of in Strapi, so there may be no code change required here. I'm going to close this for now and if we decide something different then we can reopen it.

**Comment by dhmacs** [comment]
@sterlinghirsh as of now, breadcrumbs are built from `parent` `children` relation in Strapi... So there's no way to do what you want right now.. May I ask why you want to show iPhone batteries be part of `iPhone parts` but not part of `Phone parts`?
Also, we had a discussion on breadcrumbs where we decided to only show 2/3 breadcrumbs per product list, so that might help to satisfy this new requirement. I was thinking that we could have a configurable param in Strapi to tell how many breadcrumb we want to see for the collection at hand
