### ISSUE TITLE
ProductList Hero

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1170]
Implementation issue for https://github.com/iFixit/design/issues/507

Mockup: https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=8713%3A141297

![image](https://user-images.githubusercontent.com/7053450/208202148-8ec776b2-4f16-459c-82ae-46468d6b3023.png)

We would like the ability to optionally include a hero image on ProductList pages. 

- Add an (optional) full-width Hero image to a ProductList page. I believe this addition to the ProductList object in Strapi is the only Strapi change needed. @mmarcon91 are you imagining the Samsung logo in the mockup as an additional image uploaded and oriented above the H1? Or is that part of the Hero image as uploaded to Strapi?
- H1 (Strapi Title) should be overlaid on the Hero
- H2 (Strapi Tagline) should be overlaid on the Hero, under the H1.
- Text (Strapi Description) should be overlaid on the Hero, under the H2. (The text should be larger that it is in the mockup.)

CC @dhmacs @sterlinghirsh @ifixitmaxb @kwiens

**Comment by sterlinghirsh** [comment]
I have some questions on this.

How do we format the text so that it fits in the area you want it? I see that the lines break at about 40% of the width of the image on desktop, but they go full-width on mobile, so we're expecting the text to auto-wrap. Given that, the text looks like it's anchored to the bottom which also pushes the Samsung logo around, meaning we have to have a way to separately include that Samsung logo. That would be another file upload in Strapi (logoImageAboveH1 or something).

  - Will all images of this type be formatted a special way?
  - Is there a consistent aspect ratio?
  - What happens when the page shrinks?
    - Does the whole image change or do we maintain a consistent height?
    - Is the image anchored in the middle or on one side?
  - Is the text always supposed to be white text on a dark background?
  - Is there a dark transparent overlay on the image or are we expecting the image to be pre-darkened?
  - Do we need to have control over the overlay color and text color?
  - Should we allow a separate image size for mobile? We've run into problems when trying to make a single image work at desktop and mobile widths.
  - We've also run into problems when a single image is supposed to work on large and medium desktop sizes depending on how the breakpoints work out.

**Comment by ifixitmaxb** [comment]
As long as any brand/logo text in the image is apart of the image and not actual crawlable/parsable "live" text, which would conflate our h1 and h2, I'm good. Mattia seems to have good answers to all the questions. Score! Ship it!

**Comment by jeffsnyder** [comment]
> Yes, better to have two different images to improve the loading time as well

I'd like some guidance on optimal image sizes. 

Otherwise, I'm happy with the plan above.

**Comment by jeffsnyder** [comment]
Thanks @mmarcon91 

Do we need anything else to move forward with implementation @sterlinghirsh @dhmacs ?
