### ISSUE TITLE
Typescript: possibly modernize "target"

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1243]
Our tsconfig sets `target` to `es5`. This is ancient and leads to typescript not knowing about some recent javascript features.

Next already claims they transpile and polyfill your client-side code to be pretty widely compatible and we're running on Node 16 so we should be able to set it to `ES2021`.

**Comment by andyg0808** [comment]
I'm pretty sure that `target` doesn't directly affect the language features which are available: I believe it configures which things are transpiled vs. left as-is in the code (for example, arrow functions). It has a side-effect, however: the [docs say](https://www.typescriptlang.org/tsconfig#target) it also sets the default value of `lib`, which controls which library features TS will understand to be present. As far as I know, library features are generally not affected by transpilation; they require polyfilling if we want them. So bumping `target` to `ES2021` likely also results in our app potentially using unpolyfilled library features, unless Next is polyfilling them for us. I suspect we're seeing the `lib` bump here, because as far as I know, `target` in itself doesn't affect which features can be used.

**Comment by danielbeardsley** [comment]
Yes, that's my understanding as well. Next.js support: https://nextjs.org/docs/basic-features/supported-browsers-features

So we have next.js polyfilling some stuff and we have [polyfill.io included on the page now](https://github.com/iFixit/react-commerce/blob/2b9e32d340ad90135e08b01dc641fc6a9adc0163/frontend/pages/_app.tsx#L29-L32)

**Comment by andyg0808** [comment]
Looks like the `lib` value can also include specific functions we've polyfilled, which might be the safe way to add support for those polyfills: https://www.typescriptlang.org/tsconfig#lib

**Comment by dhmacs** [comment]
Was this brought up with the intention of reducing JS bundle size by not using polyfills for older browsers?

**Comment by danielbeardsley** [comment]
> Was this brought up with the intention of reducing JS bundle size by not using polyfills for older browsers?

No, but that's a good point since we're already using `polyfill.io` we don't need the polyfills bundled.

This was brought up because typescript wasn't aware of the second argument to `new Error(msg, options)` because it's set to target es5.

**Comment by dhmacs** [comment]
> No, but that's a good point since we're already using polyfill.io we don't need the polyfills bundled.

Personally I'd prefer to let Next.js manage polyfills instead of keeping our own solution

**Comment by danielbeardsley** [comment]
> Personally I'd prefer to let Next.js manage polyfills instead of keeping our own solution

We're running an instance of the most popular polyfill service (polyfill.io), so I wouldn't call it our own solution. It also has the advantage of requiring much less JS to be downloaded (polyfills are only included if you request them and your browser needs them), it's cached, and it's [already included on the page](https://github.com/iFixit/react-commerce/blob/d528e7820d58d4f6f1ea3fd6e1f14e40ebf42f2b/frontend/pages/_app.tsx#L29-L32). 

Next.js has chosen a set of things to polyfill and they are included in the bundle whether you need them or not. We don't necessarily need them all and we've needed polyfills that are not included (See #1033).

I'm going to see how changing the target affects bundle size.

**Comment by danielbeardsley** [comment]
> In addition, to reduce bundle size, Next.js will only load these polyfills for browsers that require them. The majority of the web traffic globally will not download these polyfills. -- [The docs](https://nextjs.org/docs/basic-features/supported-browsers-features)

Oh wait... wat? Next also runs some polyfill service? Or perhaps some dynamically imported polyfill modules? Looking into it...

**Comment by danielbeardsley** [comment]
Ah, I see, they add a `<script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script>` tag that only loads that script [if the browser doesn't support js modules](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-nomodule). i.e. a relatively coarse form of polyfilling. Maybe I'm still missing something.

**Comment by dhmacs** [comment]
I just checked and Typescript now sees the second argument of `Error`:

<img width="1024" alt="Screenshot 2023-10-31 at 13 56 15" src="https://github.com/iFixit/react-commerce/assets/4640135/3ea66867-1cc3-4aa4-83c2-053d77ccd792">

So this was probably fixed by some Typescript upgrade. I've also checked on the latest version and Next.js still generates projects with Typescript target set to `es5`, but they've merged a PR to essentially ignore it https://github.com/vercel/next.js/pull/44567, given that Typescript is not being used for compilation. 

@danielbeardsley feel free to re-open if you have any actionable item in mind
