### ISSUE TITLE
Cross sell integration tests fail when run from Europe

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#1278]
Cross Sell section is initially hidden for European users until they explicitly select that they want to buy from the US store:

<img width="661" alt="Screenshot 2023-01-20 at 18 16 10" src="https://user-images.githubusercontent.com/4640135/213762482-d3506f79-db70-43ff-ac3b-8476ba236510.png">

This makes tests fail when they're being run from Europe.

## Do this

Force the US locale on the test so that tests behave predictably

cc @iFixit/qae

**Comment by mlahargou** [comment]
Cool! We can get this patched up 👍

**Comment by mlahargou** [comment]
We might be able to emulate the location: https://playwright.dev/docs/emulation

**Comment by ardelato** [comment]
I am trying to reproduce this bug but I cannot do so.

The international buy box only renders if we change the store in www.cominor.com and continue using the same browser instance to retain the cookies.

https://user-images.githubusercontent.com/22064420/215567851-8b3952e8-b632-4aa7-847f-dc9b56b4b1a3.mp4

--- 

I also tried using Chrome's Locale tool and a VPN to change my location to Italy, but that did not cause the international buy box to render either.

![IP address does not change international buy](https://user-images.githubusercontent.com/22064420/215568254-efe0f05a-91a3-4a7e-93dd-839365ad0c49.png)

---

@dhmacs are you still able to reproduce this error, if so can you provide the steps?

**Comment by dhmacs** [comment]
@ardelato Yes I'm able, and I'm not doing anything in particular, just start the dev server and run `pnpm playwright:run`

**Comment by ardelato** [comment]
I found the issue and followed up with a solution in #1319.

Here are the reproduction steps:
1. Change IP location to Europe
2. Whitelist the IP for Cominor
3. Start up the Dev Server normally and validate the BuyBox is now rendered
4. Run tests that do not have the `api/2.0/internal/international_store_promotion/buybox` mocked. 
5. Tests should timeout because `Add to Cart` is not rendered and the `BuyBox` is rendered instead. 

By whitelisting the VPN's IP address for Cominor, it allowed the requests to `https://www.cominor.com/api/2.0/` to not be denied. The IP address used to send the request to `https://www.cominor.com/api/2.0/internal/international_store_promotion/buybox` is what determines whether the international buy box should render. Therefore regardless of changing the Browser's locale or timezone, or using Playwright's [geolocation](https://playwright.dev/docs/emulation#geolocation), the IP address will be the primary condition for this component. 

As such, we need to mock this request, which we do already in one test: https://github.com/iFixit/react-commerce/blob/23f405b48ab861bb96747b2dc656edaa69f8204e/frontend/tests/playwright/product/add_to_cart.spec.ts#L6-L16
To ensure all other tests have this mock request, I moved it into the default handlers list.
