### ISSUE TITLE
Implement new header for Next.js product list pages

### ISSUE THREAD

**Issue by lithobraking** [iFixit/react-commerce#128]
## Problem

We've decided to build a new, simplified header for the collections page, rather than refactor our existing header code to work in both places. There will still need to be shared code eventually, but for the sake of an MVP we want to save the more complicated bits for later.

We'll build it from scratch with Chakra, TypeScript, Next links/images, etc. and pull in the logged-in user's info via the `/api/2.0/user` endpoint just like we do with the Shopify frontend currently.

## Do This

For MVP, the header should include:
- [x] iFixit Logo
- [x] Header categories and associated dropdown items
- [x] Search
      - Searches the US store, just like the existing product list page
- [x] Login / Join Buttons
      - Use `/login` and `/join` links instead of opening a modal
- [x] User Menu (for logged in users)
      - Do not include in menu:
          - Count for `Notifications` option 
          - `/Manage` link, or associated logic
- [x] Fix CLS issues by changing unauthenticated UI

## These have been moved after V1
- [ ] #150
- [ ] #151
- [ ] #152
- [ ] #153

## Testing notes

- links go to the correct URL
- all dropdowns work correctly

CC: @dhmacs

**Comment by lithobraking** [comment]
CC: @bhuminson @zdmitchell @kwiens

**Comment by lithobraking** [comment]
This spec should be more or less unchanged with regards to the mobile view, but the mobile header has a bit more animation going on than its full-sized counterpart, and it's probably okay if that animation isn't matched in the MVP.

**Comment by dhmacs** [comment]
@lithobraking 

- [ ] The job of the search bar basically is to redirect to the search page (e.g. https://www.ifixit.com/Search?query=repair+iphone) right?
- [ ] The store menu won't have the region dropdown right? (Since we're placing it in the footer)
![image](https://user-images.githubusercontent.com/4640135/143083425-24d309b1-5bca-4b5e-b7b4-0404a3a5625d.png)
- [ ] How can I test user login when I'm working on `localhost`? Should I work against `cominor.com/api/2.0/user`? If so, how can I signup on cominor?

**Comment by lithobraking** [comment]
1. I believe so, at least with this current iteration.
2. Right, we just need to ensure that it actually makes it into the footer.
3. I'm not all too familiar with how to get someone signed up on Cominor yet. In the meantime while I get that sorted out, is using mock user data a viable alternative?

**Comment by dhmacs** [comment]
> 3. I'm not all too familiar with how to get someone signed up on Cominor yet. In the meantime while I get that sorted out, is using mock user data a viable alternative?

I can certainly mock in order to build the UI, that is not a problem and I'm not stuck on this now.. I've just asked this in advance so when I'll need to test I know what to do

**Comment by dhmacs** [comment]
@lithobraking 

> - Use /login and /join links instead of opening a modal

https://www.ifixit.com/join gives back a 404. I'm gonna use https://www.ifixit.com/Login/register instead, ok?

**Comment by lithobraking** [comment]
@dhmacs `/register` is the correct one, my mistake!

**Comment by dhmacs** [comment]
Fetching user data client side can cause CLS since we don't immediately know if we have to render "join | login" links or the user avatar. There are a couple of solutions to this:

- **Fetch auth data server side**: this can be tricky as we would need to forward cookies (we would need also to set cookies for localhost and Vercel links in order to support local dev and testing) or build some sort of api that works without cookies
- **Redesign UI/UX (recommended)**: I've discussed this with Mattia and instead of having "join | login" links we can have a default user avatar for unauthenticated users that when clicked shows join / login links, or perhaps redirects to the login page. This way there would be no layout shift

> Note: as an optimization I've also used ```<link rel="prefetch" href={`${IFIXIT_API_ORIGIN}/api/2.0/user`} as="fetch" />``` to prefetch user data

**Comment by dhmacs** [comment]
@lithobraking 
Is it something that we can do now or should we plan it for later?

**Comment by lithobraking** [comment]
@dhmacs If it isn't too much extra labour, I'm in favour of doing it sooner rather than later.
