### ISSUE TITLE
Featured Product Pages using Strapi

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1355]
We have some special products that we want to have special pages. Right now, we have two built as one-offs:
- https://www.ifixit.com/Store/Tools/Pro-Tech-Toolkit/IF145-307
- https://www.ifixit.com/Store/Tools/Manta-Driver-Kit--112-Bit-Driver-Kit/IF145-392

We'd like to be able to build these pages in Strapi so it doesn't require dev work for every change. This requires a new collection type in Strapi: FeaturedProduct. This will be keyed on the product handle. We also need a set of configurable components to make it easy for non-devs to build these pages.

When a product page is loaded, we can query Strapi for a FeaturedProduct with the product's handle. We can mitigate additional delays by caching the response from Strapi and running the query in parallel to the Shopify API query.

We will still probably want to have some parts of the normal product page alongside the new custom components. For example, we will want to keep reviews, and we may want to keep the FeaturedProducts component (name conflict?). We may want to be able to use fields from the Shopify product in the Strapi components. For example, when we show the product's price, it should use the real price from Shopify rather than making us copy the price into Strapi.

**Comment by dhmacs** [comment]
2 notes about this:

- The product page template is already build on sections, so featured products might just be an enhancement to this. By this I mean that we can probably enhance the product model to query Strapi, to get the sections, and if there's no entry for the product we default to the standard product page set of sections
- Now that Shopify released [MetaObjects](https://help.shopify.com/en/manual/custom-data/metaobjects) I think it's worth take a look at that too, because we might be able to get these customizations without leaving Shopify. MetaObjects are much like Strapi custom components, where you can define a structure with many kind of fields, and then reference that directly from the product page.

**Comment by sterlinghirsh** [comment]
I think you're right about the product page template, though the existing Featured Product Pages have a very different layout to the normal product pages, so it may end up replacing almost all the components. Still, I expect them both to go through the same nextjs page `/products/[handle]`.

Regarding MetaObjects, I'm hesitant to embrace them right now, but admittedly I haven't dug into them much. We currently don't do any product catalogue editing in Shopify, and the plan is that at some point we'll want to expand the scope of our store so that the non-US stores are also using react-commerce. When that happens, I think we may run into problems keeping MetaObjects in sync across stores.

**Comment by dhmacs** [comment]
> When that happens, I think we may run into problems keeping MetaObjects in sync across stores.

I agree this might be a tricky part. We're looking into assigning one of our employees a new project and potentially we could build a multi store sync app. We need to brainstorm how the syncing process should work, so I'd be interested in getting your opinion on this
