### ISSUE TITLE
Make an error in a component not result in a blank page

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1655]
From Post-Mortem #1653

### Problem
A js error client-side in a user-menu component (#1654) caused the entire page to go blank.

### Do This
Start with one react error boundary at the top

**Comment by dhmacs** [comment]
This is the recommended approach in React docs: https://github.com/bvaughn/react-error-boundary

It might be difficult to create sensible boundaries for global concepts like `user`, because we might include it in other parts of the page beside the user menu.
Likely strong validation with Zod is our strongest option to fallback nicely in this scenario

**Comment by danielbeardsley** [comment]
> It might be difficult to create sensible boundaries for global concepts like user

Agreed. This issue is about isolating components, regardless of their data-sources, so that ErrorBoundary component may be a good choice to use in more places.
