### ISSUE TITLE
E2E tests fail when RBT is out of stock on Cominor

### ISSUE THREAD

**Issue by masonmcelvain** [iFixit/react-commerce#1699]
## Problem

CI fails for all pulls when the [repair business toolkit](https://www.cominor.com/products/repair-business-toolkit) (RBT) is out of stock on Cominor.

```
[Desktop Chrome] › product/pro-user.spec.ts:5:8 › Pro User Test › Pro Discount Applied to Product Price 
[Desktop Chrome] › product/product-variant.spec.ts:58:8 › Product Variant Tests › Switch Variants and Add To Cart 
```

Example [log](https://github.com/iFixit/react-commerce/actions/runs/5049723975/jobs/9059533047?pr=1698)

The workaround is to go onto [cominor admin](https://www.cominor.com/Admin/Inventory/input_new.php) and add new inventory manually. This is a pain and can happen multiple times per week.

## Do this

Figure out a way to not depend on this item being in stock, or automate it's restocking.

CC @iFixit/qae

**Comment by batbattur** [comment]
It looks like this started happening because the repair toolkit uses a new default sku. 

Prior to using MSW, we used to restock some of the products used in tests using this [script](https://github.com/iFixit/ifixit/blob/master/Tests/Exec/Commands/StockCypressTestProducts.php) by [cron](https://github.com/iFixit/server-templates/pull/3656). It stocked [`145278-14`](https://github.com/iFixit/ifixit/blob/4c264068f084045dbc03ce35510fd06af9bd491c/Tests/Exec/Commands/StockCypressTestProducts.php#L31) but the new sku for RBT is `145278-18`. 

Since we have MSW working now, we can drop the restocking logic and directly mock the item to be always in stock.
