### ISSUE TITLE
Noindex Specific Product Pages

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#1780]
We have two, if not more, use cases where we need the ability to noindex (in Google) a product page or set of product pages. If we had the ability to do this in bulk, that would be nice to have. 

Use case one: used or refurbished products that otherwise would compete with the new product page (and in some cases OEM not allowing it to be marked as genuine). https://ifixit.slack.com/archives/C5L2ZJQ69/p1687805238096969

Use case two: duplicating and tweaking a product page specifically optimized for SEM/PPC ads, but we don't want it indexed.

cc: @jeffsnyder

**Comment by ifixitmaxb** [comment]
Sounds good to me.

**Comment by masonmcelvain** [comment]
I CR'd the pull without reading the broader context, and we need to set up a new field in Akeneo to make this work. Also, we might choose to use a boolean metafield instead of an integer field ([docs](https://shopify.dev/docs/apps/custom-data/metafields/types#supported-types)).

I made a stub issue on iFixit to pick up the backend work.

**Comment by masonmcelvain** [comment]
https://github.com/iFixit/ifixit/issues/50590
