### ISSUE TITLE
`/products` 404

### ISSUE THREAD

**Issue by djmetzle** [iFixit/react-commerce#1834]
Not everyone is url-hacking, but:
https://www.ifixit.com/products
https://www.ifixit.com/products/
probably should not 404.

CC @ifixitmaxb

**Comment by federicobadini** [comment]
If ifixit.com/products is an indexed URL with significant traffic, it would make sense to consider a redirection rule. We can manage this in Next by adding an index route to avoid adding another rule at the CDN level since, as I recall, we have a limited set of rules we can set there.

On the other hand, if the traffic is low or nonexistent, I believe that the management wouldn't be particularly significant.

Let's wait for @ifixitmaxb to give us some insights for that specific url

**Comment by ifixitmaxb** [comment]
I don't care about this. Let them 404. Or 301 them both to /Store. 

[We should just have a better 404 page](https://github.com/iFixit/design/issues/493). :)

**Comment by djmetzle** [comment]
Okay, if its not important, disregard.
