### ISSUE TITLE
Header spacing and color are off

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/react-commerce#189]
Current site header:
![image](https://user-images.githubusercontent.com/33426643/157132423-a2070e9c-c586-48c8-966e-60047cd9dee0.png)

Current react-commerce header:
![image](https://user-images.githubusercontent.com/33426643/157132478-0fcba627-adef-4274-91fe-d1a645ab6013.png)

Note:
- The site logo is further right.
- The text "Fix you stuff" is further left on the site.
- The workbench, notifications, and cart icons are missing (I would expect us to at least want the cart back on the store).
- The react-commerce header is bluer. (Note, I can see this on my laptops regular 1080p monitor, but it's easier to see on my 2k oled set to gaming)

Windows browsers

**Comment by dhmacs** [comment]
I might be wrong, but I think the header is not supposed to look exactly like the current header, although I see the point of keeping it the same while we're transitioning to Next.js.

To address you feedback:

> - The site logo is further right.
> - The text "Fix you stuff" is further left on the site.

This is done to make left and right paddings consistent. The current iFixit header is slightly unbalanced toward the right, so we thought to fix this

> - The workbench, notifications, and cart icons are missing (I would expect us to at least want the cart back on the store).

We already have a preview of the new mini cart. See it [here](https://react-commerce-fvthlokma-ifixit.vercel.app/store/parts). I'll open the PR soon, I'm just waiting for the pro user API to be available.

The workbench will take a little bit more time to make it into the new site as there are ongoing discussions on its redesign.

So far we never talked about notifications, as I understand they have not been prioritised for the initial release. Anyway if you can provide me with an API and some instructions I can add them.


> - The react-commerce header is bluer. (Note, I can see this on my laptops regular 1080p monitor, but it's easier to see on my 2k oled set to gaming)

I think this is because we're trying to stick with tailwind / chakra tokens to introduce consistency. We're using core primitives though, and the color was introduces with https://github.com/iFixit/core-primitives/pull/27

Should we make a custom token for the background? Would you pick a different color from tailwind tokens? What would like to do?

**Comment by k0rvusk0r4x** [comment]
This makes sense to me. 

As far as whether we make a custom token, choose one, or something else, I think that is a Kyle question.

**Comment by sterlinghirsh** [comment]
I asked @ianrohde and he said the recently added a token `black` with the old header color in v2.4.1 of core primitives, so we should use that.

**Comment by dhmacs** [comment]
@sterlinghirsh now that we're providing a way to export packages via the monorepo, can I move the content of `react-components` into the `react-commerce` monorepo or do we still need to keep it as a separate npm package?
