### ISSUE TITLE
Discuss solutions to enable tiered pricing

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#19]
From [Slack question](https://inkofpixel.slack.com/archives/C01K32B4FPX/p1622052117025700)
> @macs @federicobadini A few weeks ago we discussed how we could implement tiered pricing using headless checkout. Did you have any ideas for how we could implement that with our current system? Our current store already can take wholesale pricing into account when displaying products, but that doesn't get passed to the Shopify checkout automatically, so the customer will get charged the normal amount. I was imagining something like keep customers tagged with e.g. Wholesale: Tier 1  and then have each product use a metafield for tier_1_price, tier_2_price etc. But I'm not sure how to make the checkout automatically use that price when the customer is tagged.

Below there are some questions to clarify the boundaries along with a few options on how wholesale can be done. To be able to know which option to pick we need to have a better understanding of your requirements, and whatever solution we pick needs to be validated since often you need to work around platform limitations to accomodate specific requirements.

## Questions

- What's the scope of tiered pricing? Is it for the iFixit Pro program? What are the use cases that we should know about?
- What kind of discounts do you make? Different price listing, volume discount, % discount, fixed discount?

### Option 1: Shopify Plus Wholesale channel

The Shopify [wholesale channel](https://help.shopify.com/en/manual/online-sales-channels/wholesale/channel) is a separated password protected store for managing wholesale orders. Although the channel provides some level of customization on the appearance of the storefront, it's pretty much limited and does not allow integration with third parties.

This is a quick solution to manage B2B customers, but if the goal is to offer a seamless experience with the main website then this is a no-go.

### Option 2: Shopify scripts

Shopify Plus allows checkout customization via Shopify scripts. So we could build checkout customization like:

- % or fixed discount for customers with a given tag
- Store different pricing on metafields and use that to populate line item properties with price details that can be used by the Shopify script to discount the product price at checkout

### Option 3: Expansion store

We can use a different store as backend for wholesale orders. Based on a customer tag we could decide which store to use to gather product pricing and we'll create checkouts on that store.

### Option 4: Use an app

We could use an app like [Bold custom pricing](https://boldcommerce.com/custom-pricing) to manage tiered pricing. We need to get access to API in order to integrate with the headless store.

cc @jeffsnyder @sterlinghirsh

**Comment by sterlinghirsh** [comment]
Option 2 seems great, but according to their docs, you can't access metafields from scripts. https://help.shopify.com/en/manual/checkout-settings/script-editor/limitations#metafields

Reading Bold's docs, I found this comparison of the three methods they use to achieve custom pricing. https://support.boldcommerce.com/hc/en-us/articles/360044716171-Discount-Methods-and-How-to-Switch

In short, you either make extra variants or have your app create a draft order and adjust the pricing before redirecting the customer. I think the latter is the best option for us, even though I don't love it overall. We would have non-pro checkouts go through the client-side checkout that we already have set up, but pro checkouts would have to go through another app like Bold or a custom thing that emulates its features.

**Comment by dhmacs** [comment]
@sterlinghirsh 
> Option 2 seems great, but according to their docs, you can't access metafields from scripts. https://help.shopify.com/en/manual/checkout-settings/script-editor/limitations#metafields

Although it needs to be validated, it seems that we can work around this limitation using cart line item properties. In short, when the customer adds a product to the cart, we store the wholesale price (retrieved from product metafield) in a line item property. This way, the checkout script will have the information needed to apply that price if the customer has a certain tag. We would need to test it to make sure there aren't any drawbacks, but in principle it should work.

**Comment by jeffsnyder** [comment]
@dhmacs I'm a bit late to the party. I think option 2 is best, I'm glad it looks like we can work around the limitation. None of the methods presented by the Bold seem like a good idea to me. 

I'll answer unanswered questions in case this information matters:

> What's the scope of tiered pricing? Is it for the iFixit Pro program? What are the use cases that we should know about?

Yes, Tiered Pricing is for our tagged iFixit Pro customers. All affected customers will have the relevant customer tag. We don't automatically tag customers, there is a manual review process with our Customer Service team that will add/remove the relevant customer tags. Customers must have a customer account to participate in the program so there will be no Tiered Pricing if not logged in and no Tiered Pricing for Guest Checkouts.

> What kind of discounts do you make? Different price listing, volume discount, % discount, fixed discount?

Different price listing and % discounts.

We have different prices set per tier, never an automatic fixed $ discount (though, we could calculate the fixed price as a discount from the standard price if that's what we need to do to make the script work). When a product doesn't have a given tier price, we automatically discount the product by a set % per tier: 

Tier 1: 10% off
Tier 2: 15% off
Tier 3: 20% off
Tier 4: 25% off

Regarding *Option 2*: 

> % or fixed discount for customers with a given tag

Are we able to set some prices to the given tiered price—and discount all other products by a given percentage?

I can't find any info about Product Tag limitations on the store level. If we're tagging every product with the given Tier 1, Tier 2, Tier 3, and Tier 4 price, we'll have 3700 new tags. And if we can't calculate the discount when a given tiered price is missing, we'd have ~1000 more tags. Maybe this doesn't matter, but I thought it worth bringing up.

**Comment by sterlinghirsh** [comment]
We're currently heading in the direction of using a private app to make draft orders. I'm about 85% confident that it will work the way we want, since that seems to be the way Bold is doing it on their side (it's one of several options they give you, but it's the one that seems most appropriate).

I'm also interested in validating the shopify script + line item property method. This would be a good trick to have in our back pocket in case draft orders have some problem we haven't accounted for, though there is a slight security risk that a customer could set their own price by adjusting the client-side code. We can mitigate this to some extent by verifying the prices at checkout time, and this could only apply to pro customers, so it's unlikely anyone would actually try to pull a fast one on us, but it is a consideration.

Using the draft order technique does not carry the same order security risk and also lets us combine a few features like store credit into the same system if we want. It also gives us an easy path to be able to apply customer discounts to manually-created draft orders (Shopify scripts don't apply to Draft Orders). For example, if a big customer like Best Buy emails us a purchase order or requests a quote, we create a draft order in Shopify manually. Then we run our app on the draft order. The app looks up their discount tier in our DB, looks up the appropriate price or percent discount, and applies those via line-item discounts in the draft order. Then, when we send the invoice or return the quote, all the prices would be correct with the discounts clearly marked without a human having to look up and set each discount manually.

> I can't find any info about Product Tag limitations on the store level.

I don't think there's a limit on how many tags we can use across the store, but each product has a max of 250 (several of which are already used for sorting, filtering, or shipping restrictions). But also remember that tags are productgroup-level, not variant-level, so it would actually be many more tags to achieve our desired result. There are a couple products with an absurd number of variants. I saw one with 69 yesterday (I think it was the 1/4" bit). While this is an outlier for sure, if we had a tag per tier per variant, that is already more than the 250 tag limit.

**Comment by dhmacs** [comment]
@jeffsnyder 

> Are we able to set some prices to the given tiered price—and discount all other products by a given percentage?

Yes , we should be.

> I can't find any info about Product Tag limitations on the store level. If we're tagging every product with the given Tier 1, Tier 2, Tier 3, and Tier 4 price, we'll have 3700 new tags. And if we can't calculate the discount when a given tiered price is missing, we'd have ~1000 more tags. Maybe this doesn't matter, but I thought it worth bringing up.

I'm not sure why product tags limitations are relevant here. The option 2 as proposed involves the use of product metafields, not tags. In our scenario one product metafield should be enough to specify all tiered prices for a product.

**Comment by jeffsnyder** [comment]
> We're currently heading in the direction of using a private app to make draft orders.

I had another chat with Sterling about this and feel I understand/am on board. I didn't realize that initiating checkout was the trigger that created the draft order, so had this fairly mixed up. 

> The option 2 as proposed involves the use of product metafields, not tags. 

Oops. You're right.
