### ISSUE TITLE
The Tools page filters are confusing

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/react-commerce#191]
The filters on https://react-commerce-ifixit.vercel.app/store/tools are confusing and unintuitive. Examples:

- "Merchandise" means any product for sale, but the options for filtering include clothing, bags, and merchandise. The merchandise subfilter is only iFixit "gear" (the term we use now) that does not fit into the other two categories. If the intent is for this category to be iFixit branded, non-tool or part products, we should go back to using "gear" or choose something that similarly expresses this meaning or shorten the word to "Merch." (I've no idea why the abbreviation "merch" is understood to mean branded products like our T-shirts while the full word "merchandise" does not mean that at all, but what is important is that the customers know where to find what they are looking for.)
- "Color" as a main filter should apply to every product as literally everything has a color. Thus, I, as a customer, would expect all product of a certain color to come up if I select it. Toolkits, for example, should all be listen if I select "black" because all of their cases are black. Yet, if you select black, a bit of our branded "gear" and a few other things are listed, but nothing else. If "color" is intended to apply only to branded "gear," it should be a subfilter under that filter.
- "Apparel size" seems odd to have as a main filter. I would expect this at a clothing or department store like Target, not a store that mostly sells tools and parts. It should be a subfilter under "Clothing," which is currently under "Merchandise."

Windows browsers

**Comment by dhmacs** [comment]
@k0rvusk0r4x I think we should revisit this feedback once the work on the new Algolia index is merged, since it is quite different from the index that we're currently using

**Comment by k0rvusk0r4x** [comment]
@dhmacs Makes sense to me to hold off if that's the case and make sure this is fixed up when Algolia is being used.

**Comment by dhmacs** [comment]
@k0rvusk0r4x FYI new index hsa been merged: https://react-commerce.vercel.app/store/tools

**Comment by erinemay** [comment]
It appears from the description above that the main filters have changed with the new index, but they still aren't great (category, main category, tool category, item type, device).


<details><summary>Current filters on https://react-commerce-ifixit.vercel.app/store/tools</summary>


![image](https://user-images.githubusercontent.com/72166715/158855946-cf05fcba-9c27-40d9-9cbb-beb8a414605e.png)

</details>

I would expect something similar or identical to the current list of main filters on https://www.ifixit.com/Store/Tools.

<details><summary>Main categories on https://www.ifixit.com/Store/Tools</summary>

![image](https://user-images.githubusercontent.com/72166715/158856096-fc2b50bc-6576-4487-a1fb-99365ba7abbf.png)

</details>

**Comment by erinemay** [comment]
/parts is a little better, but they are still confusing (category vs main category)

<details><summary>Current filters on https://react-commerce-ifixit.vercel.app/store/parts</summary>

![image](https://user-images.githubusercontent.com/72166715/158857940-c8db9238-af8a-499f-913a-5b44d9a73ee4.png)

</details>

<details><summary>Main categories on https://www.ifixit.com/Store/Parts</summary>

![image](https://user-images.githubusercontent.com/72166715/158858098-49d5f7c2-82eb-44ea-836f-b79e25c8a117.png)

</details>

**Comment by dhmacs** [comment]
@erinemay I think this is not an apple to apple comparison. The `https://www.ifixit.com/Store/Parts` screenshot is showing subcategory navigation, which in the new product list is shown like this:

<img width="1153" alt="Screenshot 2022-03-17 at 18 35 28" src="https://user-images.githubusercontent.com/4640135/158861256-ebdba746-e7e6-42ea-bdd9-5bb9f13d7692.png">

Tools and parts pages on ifixit.com do not seem to have filters.

**Comment by erinemay** [comment]
> @erinemay I think this is not an apple to apple comparison.
Tools and parts pages on ifixit.com do not seem to have filters.

@dhmacs that makes sense. Ok, ignoring the comparison, there are still filters that don't make a lot of sense. Mostly on /Tools. 

/Parts still has a couple that are a little ambiguous. `Category`, `Main Category`, and `Item Type` could all mean the same thing to a user. I had to open each one just to figure out what they meant. Do we have any specs for what these high-level filters should be?

**Comment by dhmacs** [comment]
Related Slack thread https://inkofpixel.slack.com/archives/C01K32B4FPX/p1647548156119459

**Comment by jeffsnyder** [comment]
>  Do we have any specs for what these high-level filters should be?

Items highlighted in [green in this doc](https://docs.google.com/spreadsheets/d/1tAEFU1ng3IFy35pgfqh-hWjUxoK33WjF7LEJeo_vPz4/edit#gid=1422598592) are the facets I expect to see at launch. If additional facets on this sheet are included, that's great (but my team will likely need to clean them up in Akeneo/Device Wiki). 

> a couple that are a little ambiguous

Very true! I didn't include `Category` or `Main Category` in my spec. `Item Type` is the only one want to use. 

`Category`. This Facet is pulling data from Akeneo attribute `tags`. We've replaced this single tags attribute with a set of more specific attributes in Akeneo. Once we move to the new Collections framework, this attribute will be removed from Akeneo. Please remove the Facet. 

`Main Category`. This Facet is pulling data from Akeneo attribute `tag_main_category_multi`. This is something the EU team needed but I don't remember why. Please remove the Facet.  

`Item Type`. This Facet is pulling data from Akeneo attribute `tag_item_type`. This is the good one! We will probably relabel it as `Part Type`. (As I understand it, relabeling the Attribute in Akeneo will automatically relabel the Facet in Collections)

Two quick tangents:

1) The Device Wiki Facets in my doc above haven't been worked on by my team because we don't yet have a way to bulk import data.  

2) My team hasn't put in a ton of effort on cleaning up Facet options lately because of issues relating to https://github.com/iFixit/react-commerce/issues/220 . As soon as that is done, we'll finalize the Facet options.

**Comment by dhmacs** [comment]
> `Main Category`. This Facet is pulling data from Akeneo attribute `tag_main_category_multi`. This is something the EU team needed but I don't remember why. Please remove the Facet.
> 
> `Item Type`. This Facet is pulling data from Akeneo attribute `tag_item_type`. This is the good one! We will probably relabel it as `Part Type`. (As I understand it, relabeling the Attribute in Akeneo will automatically relabel the Facet in Collections)

Should I block these client side, or are we going to remove them from the index?

cc @sterlinghirsh @lithobraking

**Comment by sterlinghirsh** [comment]
@dhmacs Actually I changed my mind. We'll be cleaning up or reworking these fields over the next few months, but for the time being, please hide `Category` and `Main Category` on the client side.

**Comment by jeffsnyder** [comment]
Ok, my team will maintain `tag_main_category_multi` so that everything plays nice. 

A note for next time this comes up. I chatted through this with @sterlinghirsh and @lithobraking . Product List Pages work currently by using `worksin` and `is_tool`. Anything with a `worksin` shows up in the Parts hierarchy. Anything with `is_tool` shows up in the Tools hierarchy. We do have products with crossover, like Arctic Silver Thermal Paste, which has both `worksin` and `is_tool = 1`. There are some technical difficulties in relying on those attributes for new Collections. But using `tag_main_category_multi` solves the problem.
