### ISSUE TITLE
Update "Frequently Bought Together" widget on ProductDetail Page

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1910]
We've seen a huge drop in "Frequently Bought Together" engagement since the new ProductDetail Page was launched. A very reasonable theory suggests that the feature is now too far down the page. 
 
![image](https://github.com/iFixit/react-commerce/assets/7053450/7fa3e74f-57f3-4a36-a1c9-d9cd2b4f2d93)

@mmarcon91 worked up a [design](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?type=design&node-id=8831-143909&mode=design) that integrates the Frequently Bought Together offer with the main BuyBox. Let's implement it! 

<img width="1048" alt="image" src="https://github.com/iFixit/react-commerce/assets/7053450/3bff6787-3184-40be-bf36-1cbcbd570467">

Implementation notes: 

1) The checkboxes pictured should be unchecked by default
2) Make sure the GA Events are copied over to the new cross-sell widget implementation

CC @sterlinghirsh @dhmacs @c00perdanny @ifixitmaxb

**Comment by dhmacs** [comment]
With @mmarcon91 we've made a few iteration on this concept in an effort to make the add to cart action more intuitive. I'll be opening a PR soon

**Comment by jeffsnyder** [comment]
I _really_ think we need to add back in the checkboxes and single "Add to Cart" CTA. This adds fuss for as customers will need to close out of the cart drawer for each additional cart add (while the cart itself is making its own cross-sell recommendations). And it's worse/disorienting on mobile where the whole screen is taken over by the cart drawer after add-to-cart. WIth a single CTA, we'll also be able to make the product image much bigger as the second/third CTAs don't need to be in the box. Also, this new way doesn't work with how we have Google Events set up. Maybe that's not a big deal, but it's a consideration.

**Comment by c00perdanny** [comment]
Agreed ^. Also, "Frequently Bought Together" should have each word capitalized:
![image](https://github.com/iFixit/react-commerce/assets/66840433/7859a932-5764-4f7c-ba30-a31828df9c4e)

**Comment by dhmacs** [comment]
Hey @jeffsnyder, let me explain how we got here. We've gone through implementing the original idea in this spec: 

![Screenshot 2023-08-25 at 17 37 48](https://github.com/iFixit/react-commerce/assets/4640135/960b3a11-058c-484a-9cfa-a1c5fec63124)

After implementing and reviewing it with @mmarcon91, we felt that there were some issues with the UX:

- The connection between the frequently add together box and the add to cart button above is a bit confusing. For example what if I've added to cart the main product and now I want to add the cross sell items below? I'm basically forced to add the product twice
- How can I add one of the recommended products? Again I'm forced to add the main product as well
- What's the default status of the selector? If all selected than the we might annoy the customer that just want the main product. If all deselected then the customer has to select the 2 products and then click add to cart
- Since the cross sell item has a link, to select the item the user needs to click exactly on the checkbox, otherwise he'll be redirected the the cross sell item product page (this can happen either because of a fat finger or because one can think that the whole box is selectable, as it frequently happen in [similar UIs](https://tailwindui.com/components/application-ui/forms/radio-groups#component-7b583a008c3fc62c0fe403d10ca042bb)).

> This adds fuss for as customers will need to close out of the cart drawer for each additional cart add

Good point. We thought about this, so @mmarcon91 added also a version that would let the user add both items with a single click:

<img width="692" alt="Screenshot 2023-08-25 at 17 59 26" src="https://github.com/iFixit/react-commerce/assets/4640135/41ad5866-d74c-4711-ab90-d1117d9653e2">

The reason it's not implemented is that we weren't sure if this is really necessary. Would you prefer this version?

> WIth a single CTA, we'll also be able to make the product image much bigger as the second/third CTAs don't need to be in the box

The dimension of the thumbnail hasn't changed compared to the original version. @mmarcon91 just made a new version with bigger thumbnails, do you prefer this?

<img width="703" alt="Screenshot 2023-08-25 at 18 10 36" src="https://github.com/iFixit/react-commerce/assets/4640135/2141e502-ea23-48f9-8645-11bbe6dc5ec4">


> this new way doesn't work with how we have Google Events set up

Can you tell me what's not working? Is is that we're not adding items as a "bundle"?

---

Let me know if you still prefer the original mockup we can go back to it 👍

**Comment by jeffsnyder** [comment]
> we felt that there were some issues with the UX

What if we moved Add to Cart under the cross-sell suggestions? [Example](https://www.fixez.com/store/iphone/iphone-14-plus/iphone-14-plus-back-glass-with-adhesive-no-logo-large-camera-hole-purple). 

<img width="1150" alt="image" src="https://github.com/iFixit/react-commerce/assets/7053450/507fd32b-7414-48ed-9df6-849201a1c586">

I'm getting into "this should _really_ be AB tested" territory. So maybe we stick with what we have until we can properly AB test? @sterlinghirsh ?

> dimension of the thumbnail hasn't changed compared to the original version

The issue is less the specific/spec'd dimensions and more how it fits in the space. If we can make the thumbnail fill the vertical space that'd be great. The updated mockup looks good to me. 

<img width="341" alt="image" src="https://github.com/iFixit/react-commerce/assets/7053450/b0c4de09-471f-44cf-8e4b-a8e956c9c86d">

> this new way doesn't work with how we have Google Events set up

> Can you tell me what's not working? Is is that we're not adding items as a "bundle"?

The way the event is structured assumes one add to cart event. @addison-grant can look into this when we have a couple days of data. We'll file a new issue for the Google Event if changes are needed.

**Comment by sterlinghirsh** [comment]
I think having the thumbnail fill more of the vertical space when the text is a single line would be good, though I'd prefer to make the height of the container smaller instead. If we can let the add to cart button move up to be on the same line as the prices there would be a lot less empty space. When the title is too long, it should wrap and push both the prices and the button down.

I agree with replacing the separate add-to-cart buttons with either a checkbox or a qty selector. I think a checkbox is just fine since I think it will be very rare that a customer will want multiple of a frequently bought together item, and making the whole box selectable doesn't allow the customer to click the link to find out more about that product. Placing them above the add-to-cart button seems like it will also help prevent customers trying to add these to the cart after adding the main product. I don't think a checkbox is too hard for customers to click. FWIW this is how Amazon does it. They have "Frequently bought together" (bought together are not capitalized btw) and there are checkboxes pre-selected for each product, but it requires clicking a separate add-to-cart button for these. I'd still like to try it with a single add-to-cart button with pre-deselected checkboxes though.

![image](https://github.com/iFixit/react-commerce/assets/589425/42ea7a01-1e67-404d-8813-c81702f95e05)


I think it would also be good to show the short description on the product.

I don't want to wait for A/B testing to iterate on this, so let's just go for it.

**Comment by sterlinghirsh** [comment]
Reopening this issue since we have some more work to do on it.

**Comment by masonmcelvain** [comment]
Related https://github.com/iFixit/react-commerce/issues/1938

**Comment by mmarcon91** [comment]
I have created a new version based on the latest feedback. https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?type=design&node-id=15354-260617&mode=design&t=1MlEnpiuIoJCNOnu-4 

I have one concern regarding the increase of spacing between the variant selector and the add to cart button and the probability that if the selector is complex (3 options) the add to cart button may go below the fold line of the page.

Even on mobile you would probably not see the add to card button at the same time with the gallery.

Let's try and see how it goes, we will also bring improvements in the future with ab tests

**Comment by c00perdanny** [comment]
@mmarcon91 What is the latest update on this? @addison-grant will need this updated so we can properly track analytics on Frequently Bought Together items.

**Comment by dhmacs** [comment]
Hey Addison, the reason is that the tracking is done at the API level, so by enabling the user to add 1 product at a time we've been using the single `product` api instead of `bundle`:

![image](https://github.com/iFixit/react-commerce/assets/4640135/dba1438b-1c53-416a-a621-6a65189911bb)

I think we can revert to use the `bundle` api for this use case, and I it should be a quick change to make. @addison-grant let me know If I can procede with this.

@c00perdanny Regarding the implementation change, we're still waiting for feedback on the new mockup that @mmarcon91  posted. The new design is not needed to fix the analytics though. 

For context this refactor brought a 4-fold increase in engagement:

<img width="872" alt="Screenshot 2023-10-04 at 09 27 13" src="https://github.com/iFixit/react-commerce/assets/4640135/a395b9fa-d9ee-49ab-ba52-05b811f2217d">

**Comment by dhmacs** [comment]
@addison-grant 

> To be clear, this is for GA4 and Piwik PRO (formerly Matomo) tracking.

Ok. There's currently an ongoing effort to configure GA4 and Piwik PRO, so I'll wait for the dust to settle and then I'll look into this.

**Comment by c00perdanny** [comment]
@deltuh-vee I see this was closed last week, but the checkboxes are still missing from the Frequently Bought Together section of product pages. Is there a certain time I can follow up on this and check once it goes Live?

**Comment by dhmacs** [comment]
Hey @c00perdanny, this was closed because a fix has been shipped for the tracking. Are the events not registering correctly now? If they're not, can you post a few examples to show how they're been tracked vs how they're supposed to be tracked?

The checkboxes new design proposal has been posted by @mmarcon91 [2 months ago](https://github.com/iFixit/react-commerce/issues/1910#issuecomment-1695680110) and hasn't received any feedback, even after a follow up:

<img width="868" alt="Screenshot 2023-10-31 at 09 46 11" src="https://github.com/iFixit/react-commerce/assets/4640135/0ec8bec7-ddde-4341-b93a-7b50e7aa7b49">

To recap, while implementing the first version we came across some flaws with the checkboxes solution:

> After implementing and reviewing it with @mmarcon91, we felt that there were some issues with the UX:
> 
> - The connection between the frequently add together box and the add to cart button above is a bit confusing. For example what if I've added to cart the main product and now I want to add the cross sell items below? I'm basically forced to add the product twice
> - How can I add one of the recommended products? Again I'm forced to add the main product as well
> - What's the default status of the selector? If all selected than the we might annoy the customer that just want the main product. If all deselected then the customer has to select the 2 products and then click add to cart
> - Since the cross sell item has a link, to select the item the user needs to click exactly on the checkbox, otherwise he'll be redirected the the cross sell item product page (this can happen either because of a fat finger or because one can think that the whole box is selectable, as it frequently happens in [similar UIs](https://tailwindui.com/components/application-ui/forms/radio-groups#component-7b583a008c3fc62c0fe403d10ca042bb)).

This is what lead us to implement what's being shipped in production now.

After some feedback from @sterlinghirsh and @jeffsnyder, Mattia posted a new mockup above https://github.com/iFixit/react-commerce/issues/1910#issuecomment-1695680110, which fixes some of these issue (add to cart button moved to the bottom) while other issues are still there (and are inherent of the checkbox solution).
I've closed the issue because no-one chimed in to give feedback, so I thought there was no more appetite for changing this, given that the current solution has provided good engagement results.
To move forward implementing this, we need someone to confirm that this is actually what we want to ship.

**Comment by c00perdanny** [comment]
@dhmacs Thanks for the recap. I'll review the tracking with Addison and we'll come back if we have any updates. We should be all set for now.
