### ISSUE TITLE
Page title in breadcrumbs is sometimes cut off on mobile

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#201]
### Description
There is very little space in the mobile breadcrumbs sub-header for the title of the page. Unless the page title is short, it gets cut off. 

### Screenshots
![image](https://user-images.githubusercontent.com/72166715/157341355-d9583af7-f23e-4c83-b11c-77c1fad78012.png)

<details><summary>Macbook Pro 14" 2021 Parts</summary>

![image](https://user-images.githubusercontent.com/72166715/157341291-061886a8-9b9f-43f6-851a-c29256f73ac1.png)

</details>

### Additional Details
Present on most common devices:
- iPhone 12, 13 - Safari
- Samsung Galaxy 21, 22 - Chrome

**Comment by dhmacs** [comment]
@erinemay 

I've discussed this with Mattia when we implemented this, and we think this is the best tradeoff and should not be an issue for the viewer since right below the bar there's the full page title. 
The only other option would be to hide it from the bar entirely, but still you got to have a fallback behaviour for very long titles.

How would you handle this differently?

**Comment by erinemay** [comment]
> How would you handle this differently?

Hmmm, yeah. That's a difficult one. I don't really have an elegant solution ready. Ellipses would cut off too much of the visible text. Pulling the title out entirely probably makes the breadcrumb button less intuitive.

@lithobraking @Annika29, thoughts?


![image](https://user-images.githubusercontent.com/72166715/157908252-7fb1639f-ac1a-4e12-94a5-30486cfab205.png)

**Comment by dhmacs** [comment]
We're going to remove the breadcrumb current page on mobile
