### ISSUE TITLE
Collection page review (June 2021)

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#27]
Here's a review of the collection page status:

## inkOfPixel todos
- [x] #11  
- [x] #33
- [x] #28
- [ ]  #8 [BLOCKED]
- [ ]  #13
- [ ] #29 

## Blocked on iFixit

- [ ]  #31
- [ ] #32
- [ ]  #26 
- [ ]  #15  
- [ ]  #14 
- [x]  #16 
- [ ] #34

**Comment by kwiens** [comment]
Wikis API has documents: https://www.ifixit.com/api/2.0/doc/Wikis#content

Schematics are not in the API but will be.

**Comment by evannoronha** [comment]
> Schematics are not in the API but will be.

I'm not sure what you mean by this, but Schematics are currently served by the API. They are just not documented. The endpoint is available to the public: https://www.ifixit.com/api/2.0/diagrams/418

**Comment by kwiens** [comment]
Sweet! How do you get a list of diagrams for a device?

**Comment by evannoronha** [comment]
> Sweet! How do you get a list of diagrams for a device?

CR this pull to find out: https://github.com/iFixit/ifixit/pull/38255

**Comment by dhmacs** [comment]
> > Sweet! How do you get a list of diagrams for a device?
> 
> CR this pull to find out: https://github.com/iFixit/ifixit/pull/38255

Hi @evannoronha, I don't have access to this repo. Can you give me instructions on how to use this endpoint?

**Comment by evannoronha** [comment]
Sure thing! As of right now, I don't think you'll get much use out of it because the set of devices for which we have schematics _and_ parts to sell may be empty.

Regardless, here's the basics:
Some of our device pages have schematics on them. For example: 
https://www.ifixit.com/Device/Makita_Chain_Saw_EA6100PR_2017
https://www.ifixit.com/Device/Toro_Stump_Grinder_22615HD_2018
https://www.ifixit.com/Device/Dewalt_Impact_Wrench_DCF899HB_2016

On ifixit, we also can link to a specific diagram:
https://www.ifixit.com/Device/Makita_Chain_Saw_EA6100PR_2017#diagram/16072

Schematics are comprised of 0-n diagrams and an additional list of parts not associated with a diagram. They are represented by the `diagrams` field on the API endpoint for devices:
https://www.ifixit.com/api/2.0/wikis/CATEGORY/Barreto_Trencher_E718MTH4S_2016
https://www.ifixit.com/api/2.0/wikis/CATEGORY/Makita_Chain_Saw_EA6100PR_2017

That endpoint should give you enough information to render a summary view of a schematic:
![image](https://user-images.githubusercontent.com/6803522/127369853-76d7d957-5e48-42ef-8c2e-b0ef08196573.png)


Each diagram contains an image and a set of data points that indicate what each component on the diagram is. You can fetch all this information about a diagram from the diagrams endpoint:
https://www.ifixit.com/api/2.0/diagrams/16072

The diagram endpoint returns JSON that looks like this:
![image](https://user-images.githubusercontent.com/6803522/127370314-990d25bb-f0f3-421e-888b-040c978f778a.png)

That should give you enough information to render a full diagram view:
https://www.ifixit.com/Device/Makita_Chain_Saw_EA6100PR_2017#diagram/16072

![image](https://user-images.githubusercontent.com/6803522/127370571-60400482-c633-4778-b259-189fa3cd7058.png)

The `data` field on the digrams endpoint represents the coordinates on the image. Each coordinate has an X-Y location and radius which represents where the data point is on the image. There can also be 1 or more `item`s on the data point. An item represents a physical part that goes in a device, like a battery, belt, bolt, wheel, screen, etc. Generally, those are the things we sell. Every `item` on a diagram has a corresponding Item wiki (https://www.ifixit.com/Item/Makita_Suction_Head_Dpc7001_010114010):
![image](https://user-images.githubusercontent.com/6803522/127371000-7c75fea4-4281-4573-9e4d-579ee8d75799.png)

**Comment by dhmacs** [comment]
> Sure thing! As of right now, I don't think you'll get much use out of it because the set of devices for which we have schematics and parts to sell may be empty.

Ok then I'll pause this task until we figure out the data side.

> On ifixit, we also can link to a specific diagram:
> https://www.ifixit.com/Device/Makita_Chain_Saw_EA6100PR_2017#diagram/16072

Oh wow, this is really cool! 💯 I like the idea, it looks like a great shopping experience too 👍
