### ISSUE TITLE
Make most facets single-select instead of checkboxes

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#374]
It's rare that we want to select products that match multiple values of the same facet. When someone selects a facet value, hide the list of other values.

**Comment by dhmacs** [comment]
I'm discussing this with Mattia, and we think we're making assumptions about this, but we don't really know if that's the case.. For example a user might want to select multiple price ranges, or might want to select a new hard disk by selecting multiple capacity sizes and check which one represents the best deal.
Overall we think that hiding all the other facet values limits user ability to filter through a collection. Our opinion is that we should try to not restrain too much the user ability to filter, so that we don't inadvertently make it difficult to perform some filtering patterns.

**Comment by erinemay** [comment]
@dhmacs, When @sterlinghirsh and I were talking about his, `price` and `capacity` came up as two items that should remain multi-select. 

After thinking about it a little further, I believe `Part or Kit` chould also remain a multi-select. It's a little unclear to the average purchaser what those options mean, and I can see someone selecting both `Part only` and `Retail part only` or all the fix kit options if they want a fix kit. 

`Item type` could also be a contender for remaining multi-select. I can imagine narrowing down your search and wanting different items for the same device, like searching for a new screen and also wanting a screen protector. 

I'm less sure about those last two, but `price` and `capacity` should definitely remain multi-select.

**Comment by sterlinghirsh** [comment]
We're going to fix the options on Part or Kit, so it should end up just being two options. With that in mind, I don't think it's necessary to make it multi-select. I think let's just make price and capacity multi-selects for now.
