### ISSUE TITLE
Next Links: Back button reloads the whole page

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#425]
### Problem

I thought the next back button was just supposed to ping the props endpoint and be a faster transition. I wasn't expecting it to blank the whole page for a second or two.

### Repro
1. Visit: https://es.ifixit.com/Parts/iPhone
2. Click a subcategory
3. Click "back" via your browser
4. Slower and more abrupt than following the link in step 2 (which must just replace the props)

**Comment by dhmacs** [comment]
Unfortunately this right now is by design to patch the Algolia bug on routing. This happens because Algolia routing doesn't play well with Next.js routing (see [this issue](https://github.com/algolia/react-instantsearch/issues/3506)) . I've experimented with implementing a custom history, but it was taking too much time so I've employed this trick.
Another possible solution is to manually maintain the url as suggested [here](https://github.com/algolia/react-instantsearch/discussions/3376#discussioncomment-2297218).

If you come up with a better solution that would be awesome, otherwise we'll keep trying new package versions until the issue is fixed and we can drop this patch.

**Comment by chr-ge** [comment]
@dhmacs What trick are you referring to that you've employed?

**Comment by dhmacs** [comment]
@chr-ge To force a full page reload when the back button is pressed (instead of relying on client side navigation)

**Comment by sterlinghirsh** [comment]
I wonder if we could abandon the back button hack if we make the links normal links instead of NextLinks as in #818

**Comment by dhmacs** [comment]
You mean having the page fully reload on every filter link click?

**Comment by sterlinghirsh** [comment]
No I'd rather not fully reload. I was imagining having Algolia manage the url there, but I remember now there was a problem with that approach if both Algolia and next want to handle the back button.
