### ISSUE TITLE
Parts homepage Item Type facets have checkboxes

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#439]
From the /Parts homepage, the Item Type facets are more like all other facet types, with the checkboxes, rather than how Item Type facets behave everywhere else where they're hyperlinks. Also, when you select the Item Type facet, it adds the current-refinement element, which is, again, different than how Item Type facets behave everywhere else. 
![image](https://user-images.githubusercontent.com/86265382/178803789-48544291-3af2-49da-9879-50f451cf7486.png)
![image](https://user-images.githubusercontent.com/86265382/178804135-ad09bbcf-7274-4221-b0ca-a38817abeff7.png)

**Comment by dhmacs** [comment]
@ifixitmaxb  It's by design, as we don't have a `All accessory` product list to link to. Item types product lists are only related to devices (e.g. iPhone accessories).
See my comment [here](https://github.com/iFixit/react-commerce/pull/380#issuecomment-1172858932)

Feel free to re-open this issue if you want to have also generic item types product lists

**Comment by ifixitmaxb** [comment]
Makes sense!

**Comment by dhmacs** [comment]
@ifixitmaxb yes, like a marketing product list
