### ISSUE TITLE
Decide how to clear the collection search query

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#52]

**Comment by ardelato** [comment]
> Absolutely, we should list the search string as an applied filter, and clear it when we clear the filters 👍
I'll track this #52

@dhmacs I am not sure if the search string should be tied with the filters.

Reason is I can see the following use case for the separation of the two:

1. I am in the `collections/macbook` page and don't want to transverse the subcollections to find stuff related to **Macbook Pro 15** nor does the filter list an option for that model, therefore I search for `Macbook 15` 
2. I then select the type of item I want, say I want a `Battery`, so I select it in the filters list
3. I then want to get a price range of `$50-75` so I add that to the applied filters
![macbook 15 battery search](https://user-images.githubusercontent.com/22064420/126827833-10c6c6b2-6f04-46c8-ab3e-7b86d421dd43.png)
4. Now once I find the battery I want for the Macbook Pro 15, I want to now get screws to replace the ones I lost and will need to insert when I replace the battery.
5. I therefore clear all applied filters but still want to look for items under `Macbook 15`
6. When clearing the filters, I still see items related to `Macbook 15` and then select `Screws` in the filters list. 
7. I can now select screws that are for the `Macbook 15`

![Screw selection](https://user-images.githubusercontent.com/22064420/126828110-1fc253aa-8f74-4aa3-af1d-55d0f97a6315.png)

**Comment by dhmacs** [comment]
@ardelato I don't know, it seems an argument that can be applied to any other filter as well. 
For example let's say that I only want to shop for items that are new, so I select condition "New" as filter and I filter for batteries. Then to search for screws if I'll hit the "clear all" filters button, I'll lose the condition "New" filter. 
I think that if the customer wants to keep a given filter it does so just by removing the others one by one.

Moreover the applied filters serve another purpose, namely just by looking to them I know what the current product selection is about.

I'm ready to change my mind tough if you are sure that search should be treated as a special case

**Comment by ardelato** [comment]
I guess it depends on how the search functionality is going to be used in conjunction with the collection pages as well as the overall goal of these pages.

To elaborate, let's look at Amazon. Amazon sells different types of products, while we sell replacement parts and tools. Therefore, we have a narrower scope in categories (which are grouped as Parts and Tools). That said, iFixit users aren't looking for a `Samsung S7` to purchase but a particular part for their Samsung S7. In order to do that, they at least need to know the name, and/or model of their Samsung Phone. They can't simply search for `Samsung S7` and get relevant results--currently. They need to continuously step into collections to find any relevant parts. 

Now with that in mind, if an iFixit user already knows they need a Samsung S7 Battery, they need to step into the following collections `Parts->Phone->Android Phone->Samsung Android Phone->Samsung Galaxy Phone S->Samsung Galaxy S7` 

Then they now have a list of products that is related to the Samsung S7 collection. From here, they can now make use of the search field and search for `battery`. Therefore having this search text now be a part of the applied filters makes sense.


https://user-images.githubusercontent.com/22064420/127372362-bcc9c2b7-ec56-4b01-93e4-4898582bec4a.mp4 

https://user-images.githubusercontent.com/22064420/127372813-ce3d8abe-4167-4aba-84bb-39108f427f6f.mp4

Now consider an iFixit user who is trying to repair an S7, or multiple S7s, with different issues. If the search field functions as an all search that returns all and any part related to an S7, then clearing the search field would not be useful with the current behavior of the `Item Type` filter. If they need both a new screen and a battery the need to clear the item type before they can filter for the other. 

https://user-images.githubusercontent.com/22064420/127373115-cd24251e-ba9b-4433-a73d-0b69b69fb68d.mp4


--- 

@dhmacs 
Overall, my question is now what is the intended behavior for the search bar and will users only be able to look for specific parts by transversing the collection pages? 

Also, if you think it'll be easier to talk about, I'm down to have a Slack or Zoom call.

**Comment by dhmacs** [comment]
@ardelato 

> To elaborate, let's look at Amazon. Amazon sells different types of products, while we sell replacement parts and tools. Therefore, we have a narrower scope in categories (which are grouped as Parts and Tools). That said, iFixit users aren't looking for a `Samsung S7` to purchase but a particular part for their `Samsung S7`. In order to do that, they at least need to know the name, and/or model of their Samsung Phone. They can't simply search for `Samsung S7` and get relevant results--currently. They need to continuously step into collections to find any relevant parts.

I think this currently is just a data issue that will be solved.. When the root "parts" collection will be populated with products the user will be able to search for Samsung S7 without having to step into subcategories.

> Also, if you think it'll be easier to talk about, I'm down to have a Slack or Zoom call.

Sure 👍 Any time next week. Let's do next monday if you are available
