### ISSUE TITLE
Font performance: appears to be hurting LCP and TBT scores

### ISSUE THREAD

**Issue by davidrans** [iFixit/react-commerce#559]
I ran a couple SIte Performance checks:
- https://www.webpagetest.org/result/220801_BiDcWE_C7G/
- https://www.webpagetest.org/result/220801_BiDc52_C8N/

Here's a video showing that the LCP on mobile is being held up waiting for a font: https://www.webpagetest.org/video/view.php?tests=220801_BiDc52_C8N-r:1-c:0

https://www.webpagetest.org/vitals.php?test=220801_BiDc52_C8N&run=1
![image](https://user-images.githubusercontent.com/806152/182208733-59898227-2575-4435-9468-18a55439b7ac.png)

CC @federicobadini

**Comment by federicobadini** [comment]
## LCP
I was not able to replicate the high LCP values detected on WebPageTest either on Pagespeed insight or on GTMetrix.
It seems to be something that only on WebPageTest scores so high. See for instance the Pagespeed report here:

<img width="1027" alt="Screenshot 2022-08-02 at 10 58 58" src="https://user-images.githubusercontent.com/7805759/182335890-922ae889-6e82-4c94-9887-2ecfd713a0b0.png">

Moreover I see some discrepancies in the values that WebPageTest reports (see picture below):

<img width="1441" alt="Screenshot 2022-08-02 at 10 51 55" src="https://user-images.githubusercontent.com/7805759/182334688-c4685552-f04f-4ece-9b14-a1e4bf4ee45d.png">

I'll send anyway a PR to optimize font loading

## TBT
TBT should depend on main thread locks due to js parsing and evaluating. So to lower that score we should focus on reducing js.
