### ISSUE TITLE
Govinor (Test Strapi) should use Cominor (Test Akeneo) data

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#560]
Make it so www.cominor.com/Parts connects to main.govinor.com, uses www.cominor.com for iFixit's api, uses dev_product_group_en Algolia index, and uses development react-commerce deployment on the main branch.

--
Original issue from Jeff

strapi.ifixit.com/admin manages Strapi pages that are live on ifixit.com. These pages use live data managed in akeneo.ifixit.com.  

main.govinor.com/admin manages Strapi pages that are in our test environment on Cominor.com. But, these pages use live data managed in akeneo.ifixit.com. And, clicking on any Product in a ProductList takes you to the detail page on iFixit, not Cominor.

We need to be able test new page types, filters, etc. in a test environment with test product data provided by Cominor.

Right now, for example, I'm trying to test that our Samsung landing pages will be filtered to OEM-only when we activate products tomorrow. I am unable to do that without activating these products live, which I shouldn't do. (We're confident the filters are working properly because we did test live last week on a very limited product set, but this category of problem will continue to come up.)

CC @sterlinghirsh @dhmacs

**Comment by dhmacs** [comment]
> govinor.ifixit.com/admin 

`govinor.ifixit.com/admin` leads to a 404 for me. If you're trying to access some Govinor Strapi instance, visit `govinor.com` and pick either `main` or a specific one when you want to test on newer branches

> manages Strapi pages that are in our test environment on Cominor.com. 

What do you mean by this exactly?

> But, these pages use live data managed in akeneo.ifixit.com. And, clicking on any Product in a ProductList takes you to the detail page on iFixit, not Cominor.

I picked one of the Vercel previews and it's showing product links to cominor.com. Which Vercel preview are you using that displays ifixit.com product links?

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4640135/182341339-59ecbe79-cbf3-4887-9e3e-d3ed873875a4.png">

> I'm trying to test that our Samsung landing pages 

What are these landing pages? Are these product lists?

**Comment by masonmcelvain** [comment]
> Make it so [www.cominor.com/Parts](http://www.cominor.com/Parts) connects to main.govinor.com, uses [www.cominor.com](http://www.cominor.com/) for iFixit's api, uses dev_product_group_en Algolia index, and uses development react-commerce deployment on the main branch.

The only thing that needed to change here was the Algolia index, everything else was already correct.

### Environment variables

I dropped the `NEXT_PUBLIC_ALGOLIA_PRODUCT_INDEX_NAME` override in the `react-commerce` dashboard because we default to `dev_product_group_en` in `.env.production`:

https://github.com/iFixit/react-commerce/blob/63ba9d2d8f534ac8f94c6a37aa321a259e54ed30/frontend/.env.production#L21

Before:

![image](https://user-images.githubusercontent.com/52104630/183443422-68822191-107a-4f61-83ad-0cb44510c98d.png)

After:

![image](https://user-images.githubusercontent.com/52104630/183443650-d3fa4d79-9607-434b-957a-786245d07cc8.png)

### Routing

Additionally, we already point `www.cominor.com/Parts` (or Tools, Shop, _next) to `react-commerce-ifixit.vercel.app` (an alias for the deployment that tracks the `main` branch). So there was nothing to be done here.

https://github.com/iFixit/ifixit/blob/60c8dd431a91ceaeff7cecd74ec50cee90d7a506/Conf/haproxy/haproxy.development.cfg.php#L146-L152
