### ISSUE TITLE
Some filters are not populated/associated correctly

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#58]
Example is the Part Only items → MacBook 12" Retina (Early 2016-2017) Trackpad option 1 is marked as a Part Only but is not seen in the filters page.

https://user-images.githubusercontent.com/22064420/126720323-df1ddff9-132f-4a2b-8d8d-8a726156fb81.mp4

**Reference:** https://github.com/iFixit/react-commerce/pull/46#issuecomment-885822777

**CC:** @evannoronha and @sterlinghirsh

**Comment by sterlinghirsh** [comment]
Interesting. This is happening because we use "part or kit" as a variant axis on Shopify sometimes, but not for this product. Usually it is used to distinguish between variants within a product group, but since all the variants are "part only", we never pass that along. We could try to fix this by adding a product tag in cases where it isn't also a variant axis. Then it would be set on all parts at least. Though I don't know if having it be a tag on one product and a variant option on another would cause a problem for algoilia's filtering.

**Comment by dhmacs** [comment]
> Though I don't know if having it be a tag on one product and a variant option on another would cause a problem for algoilia's filtering.

Yes it would cause problems because we'd have to complicate the filtering logic.. I suggest to always use that variant option, or alternatively to add the tag to all products, so that we can rely on just one facet

**Comment by sterlinghirsh** [comment]
We definitely can't add the tag to all products since some of them will have that variant option. I'm not sure we can rely on always having that variant option since there may already be 3 options but I'll look into it.

**Comment by dhmacs** [comment]
> We definitely can't add the tag to all products since some of them will have that variant option.

@sterlinghirsh Can you elaborate on this? Why can't we have both the variant and the tag in this scenario?

**Comment by sterlinghirsh** [comment]
Imagine two product groups and their variants:
- iPhone 6 Screen [1 variant]
  - iPhone 6 Screen (New)
- iPhone 6 Battery [2 variants]
  - iPhone 6 Battery (New, Part Only)
  - iPhone 6 Battery (New, Fix Kit)

If we use tags, then because tags are at the product level, the first product would be fine, but the iPhone 6 Battery would get tagged with Part Only, even though one of its variants is a fix kit. I suppose in that case we could tag it with both Part Only and Fix Kit, though that would make the search refinement useless since both Part Only and Fix Kit products would show up regardless of which option was selected.

This may be an argument for using a custom Algolia index instead of relying on their Shopify app if there's no good answer here. Algolia's app does have the ability to specify variant-specific tags via a special tag format, though we have avoided using that so far.

**Comment by dhmacs** [comment]
> I suppose in that case we could tag it with both Part Only and Fix Kit, though that would make the search refinement useless since both Part Only and Fix Kit products would show up regardless of which option was selected.

Exactly, In my opinion this is not bad. The user can then navigate to the product page and select the variant according to his needs

**Comment by sterlinghirsh** [comment]
Well then why show the search refinement at all? It would seem like a bug if the user selects fix kit but then there's no fix kits available. Unless we take the union of all option values except for variant text and add them as tags. We'd get a lot of "New" but maybe that's not bad.

**Comment by dhmacs** [comment]
> Unless we take the union of all option values except for variant text and add them as tags.

Yes, this is what I'm thinking. If we add a tag for each variant, then every product that has at least 1 variant the matches a given tag would appear in the results. The other way around, is to split the variants into different products, so you won't have the same problem anymore, but I suppose this will affect other use cases.

**Comment by sterlinghirsh** [comment]
I made an issue to address this: https://github.com/iFixit/ifixit/issues/39563 . Right now the issue says we'll add the "Part or Kit" and "Condition" value for every product. Once that is working, I think we can stop including the "options" as refinements. Were there any other weird fields like those?

**Comment by dhmacs** [comment]
This issue seems stale. @sterlinghirsh @ardelato what's the next action here?

**Comment by lithobraking** [comment]
@ardelato Is this solved now that #39563 is merged?

**Comment by ardelato** [comment]
@lithobraking I can't say for sure because I successfully reproduced the error on the Vercel preview for the latest merged PR https://github.com/iFixit/react-commerce/pull/120

@sterlinghirsh is there anything else we need to do on our end or @dhmacs is there a different Vercel link to use to validate this?

**Comment by sterlinghirsh** [comment]
I think we addressed the main issue. It might not be reflected yet, but we're going to end up getting rid of the filter you mentioned anyway. I'm going to close this for now and we'll reevaluate after #40255 is done and the frontend is updated to reflect it.
