### ISSUE TITLE
Design: Featured Subcollections

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#74]
Our device parts collection page designs currently include links to the parts collections for child devices (e.g. iPhone Parts > iPhone 7 Parts). We want to be able to link to other featured collections that will be custom-added via Strapi or similar (e.g. iPhone Parts > iPhone Batteries). These other collections will come with a title, image, url, and possibly a short piece of text. I think it should go under the product list, but before the warranty banner. We should be able to support 0-3 of these on the page. This will probably not be in our initial release, but it would be nice to get started on the design.

**Comment by dhmacs** [comment]
@sterlinghirsh 
> We should be able to support 0-3 of these on the page.

What do you mean by this? Do you mean that we should be able to have 0 or 3 sections each containing a list of subcollections, or do you mean that we should have only 1 section containing up to 3 subcollections?

**Comment by sterlinghirsh** [comment]
1 section

**Comment by dhmacs** [comment]
@sterlinghirsh Mattia has updated the [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit-Shopify-Working-Files?node-id=501%3A7165). See "collection 6" for the preview of the featured sub-collections.

Due to the aspect ratio of the images, sub-collections take quite a bit of space when combined with descriptions. Do you think descriptions are necessary? What's the purpose of these descriptions? Will they help the user in the navigation? On the data side, do we have these descriptions? They should be quite short to avoid taking way too much space.

Along with the proposed design, Mattia suggests also to use horizontal scrolling for subcategories, so that the user can get faster to the products. What do you think about this? I know we discussed about this previously, but I thought I'll bring this up again since Mattia suggested it. If you like the grid view more, then no problem 👍

**Comment by sterlinghirsh** [comment]
Thanks for the update. I think we can make the images smaller like on the other subcollection pages. For the descriptions, I don't know if they're necessary. I'm fine with dropping them. I agree they take up too much space as-is. I'd also move them way lower on the page, maybe under related new stories. In my opinion, these links are mostly useful for Google, so I'm not worried about them being super prominent for humans.

As far as horizontal scrolling, I'm curious to see how that would look on Mobile for child devices. My worry is that if there are many child devices (50+), it could be annoying to scroll that much, especially if you can only see one child device at a time while scrolling. But if you have something in mind, I'm curious to see. On desktop, I think horizontal scrolling is a little less natural, so showing the grid view still makes sense, though again if you have an idea then show me what you got.

**Comment by dhmacs** [comment]
@sterlinghirsh Mattia agrees that if the sub collections can be so many then it's better to avoid horizontal scroll. The mockup has been updated with the changes you've requested
