### ISSUE TITLE
Product Page: Improve UX of trying to change variants when some are OOS

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#788]
When selecting variants, the `Condition` option shows all the possible (in stock or (oos and `disable_when_oos` = true)) options. Of those options, users can only click on options that have available items matching all the other selected options. 
https://react-commerce.vercel.app/Products/iphone-11-pro-screen
![image](https://user-images.githubusercontent.com/72166715/194409085-bf93da97-aa1d-429a-96fb-e420ca768465.png)

For example, if I want that `Used, B stock` item ⬆️, it's unclear why that item is not clickable. My first assumption would be that it's not available. After clicking the Part option, there's no indication that the `Used, B stock` is suddenly available. 

I would expect to be able to select that `Used, B stock` option and have the appropriate variant availability load ⬇️ 
![image](https://user-images.githubusercontent.com/72166715/194409310-ae346aa5-4783-4d34-bee3-43593fe915ae.png)

I would expect this for all the options available. The first option I choose is probably the most important to me, and I would want to see all the available combinations for that specific option. 

### Note:
This experience of choosing variants was improved by https://github.com/iFixit/react-commerce/pull/774, so I'm going off of that branch and not main.

**Comment by erinemay** [comment]
Also, the difference between unavailable and available option text color is subtle. I try to click on that second option all the time while testing and find out that it's unavailable because I can't click on it. This can be a separate issue, but it just adds to the confusion around what's available and what's not. 

![image](https://user-images.githubusercontent.com/72166715/194412937-df17d8c6-79e7-4a0e-80cd-64769135a8fb.png)

**Comment by sterlinghirsh** [comment]
We solved this in our shopify-v2 theme in a way that I think is good enough. We made it so if you select an option that is incompatible with other selected options, we update the other option selections to the closest matching product. For example, if you have Fix Kit / New selected, and you select Used, it auto-switches Fix Kit to Part Only since there's no Fix Kit / Used.

There are tradeoffs, of course. There's a slight potential to be confusing, but I don't want to show non-existent products, and I also don't want to show unselectable options.
