### ISSUE TITLE
Add link to battery disclaimer

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#831]
https://react-commerce.vercel.app/products/google-pixel-3a-xl-replacement-battery-genuine

![image](https://user-images.githubusercontent.com/72166715/195732169-e876f8dc-ad37-4078-9e9d-daffbf3a63bc.png)

`Learn more` should link to https://www.ifixit.com/Wiki/What_to_do_with_a_swollen_battery

Legacy page: 
![image](https://user-images.githubusercontent.com/72166715/195732549-e239e40d-7f1c-4289-aee0-2b4b88f9a56d.png)

**Comment by sterlinghirsh** [comment]
This is indeed a data issue. There's a wiki render setting in ProductBodyFactory where we disabled rendering links for AU/CA, and US inherited that setting. I don't remember why we set it like that, but I'm going to see if we can switch that. In the mean time, I'm going to close this issue, since there's nothing to do on the frontend. Good catch @erinemay

**Comment by sterlinghirsh** [comment]
Opened https://github.com/iFixit/ifixit/issues/45171 to address this in the data.
