### ISSUE TITLE
Gray-out unavailable product variant options

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#844]
With https://github.com/iFixit/react-commerce/pull/838, we got the ability to click on "unavailable" variant options and have it switch the other selected options so that you are on a valid variant with the option you selected. It works great!

The final step to getting us parity with the live site is to set the options to being grayed out as before https://www.cominor.com/Store/Tools/Fix-the-World-T-Shirt/IF179-068?o=1, but selectable and behaving as in https://github.com/iFixit/react-commerce/pull/838

So unavailable options are shown to be unavailable by being grayed out, but still clickable. 
Like in this case, the available sizes are grayed out to show that they unavailable with the other options, but when I click on one, it switches variants according to the snazzy logic in https://github.com/iFixit/react-commerce/pull/838. 
![image](https://user-images.githubusercontent.com/72166715/196541350-7f5c9732-7ce1-4296-a55d-26e378c5fc46.png)

cc: @sterlinghirsh @federicobadini

**Comment by erinemay** [comment]
Honestly, I'd love some other indication or way to make it a little clearer that the unavailable item is selectable (maybe like this ⬇️?). But, that wasn't spec'd, and it would go beyond getting parity with the current product page variant selection. 
![image](https://user-images.githubusercontent.com/72166715/196543473-c5b9961a-9ddf-4df9-8eeb-1677cacfd394.png)

**Comment by federicobadini** [comment]
A couple of questions on this:
The actual implementation is done via native `select`. Native selects do not allow to obtain the desired behaviour.
Browsers in fact do offer a very limited styling configurations for select options: see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option).

Since Chakra uses native select, this means that if we want to obtain such behaviour we need to use a custom select component instead of the native one (with all the implications that this choice bring wrt mobile interaction).
On `ifixit.com` I see that you are already using a custom implementation but I was asking myself if we wanna follow the same path also here.

We also have to consider that Amazon - that uses the same approach of greyed out clickable options - has a different ui for mobile: see [here](https://www.amazon.com/CLARKS-Womens-May-Marigold-Leather/dp/B0125LSKXU/ref=sr_1_6?crid=1VKYF89OQ0E7F&keywords=shoes%2Bfor%2Bwomen&qid=1666364096&qu=eyJxc2MiOiIxMy41MCIsInFzYSI6IjEzLjQzIiwicXNwIjoiMTIuNjAifQ%3D%3D&sprefix=shoes%2Caps%2C214&sr=8-6&th=1)
So maybe they found out that the custom built dropdown is not converting great

**Comment by sterlinghirsh** [comment]
Using the editable example on chakra's site, it looks like it works for me in chrome:
![image](https://user-images.githubusercontent.com/589425/197252178-e1f80678-65e2-4fbf-8b6a-b4280d52f6a4.png)

Oddly, it works with `style={{color:'blue'}}` but doesn't work with `color="blue"`. Worst case it doesn't show up gray for some users. I think for this release, that will be okay and we can adjust it later if we want.

For non-dropdown options, I like the gray dashed border and grayed (or reduced opacity or desaturated) image / text.

**Comment by federicobadini** [comment]
I have opened a PR including the required changes.
Even if specified via `style` parameter however only Windows machines allow to customise the option color.
OSX, iOS and Android OS all use their own picker without the possibility to differentiate the color of an option
