### ISSUE TITLE
See if we can stop using react-commerce-prod

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#849]
Now that we have the ability to pull live strapi data into dev strapi, we have much less use for react-commerce-prod branch previews. These have caused quite a few headaches, including indexing issues and CORS issues. Can we use a specific deployment on react-commerce for production rather than continuing to have 2 vercel projects?

**Comment by danielbeardsley** [comment]
The problem with going down to one vercel project is that `www.cominor.com` would no longer have a "deployment" on vercel that uses the correct config (talking to cominor for the API, govinor for strapi, ...).

We have needs:

* Prod (talks to ifixit.com api, strapi.ifixit.com, shopify ifixit-us store)
* Dev (talks to cominor.com api, govinor strapi, shopify ifixit-test store)
* Preview branches (as close to prod as is possible so QA is effective)

There's not a convenient way to cover those needs with one project.

Baking the config into a JSON file in the repo (then choosing which to load based on incoming hostname) would *function* but it would break caching (caching is shared and we could serve dev pages to prod users).

I don't see how we can accomplish this. I also don't think it's important that we reduce down to one deployment (especially since it seems we can't), so just leaving it at two projects is fine with me.

**Comment by sterlinghirsh** [comment]
I thought we could set up a second deployment on react-commerce with separate environment vars. I'm not sure we need to have 2 preview branches (prod preview and dev preview).

**Comment by danielbeardsley** [comment]
I created two projects because there didn't seem to be any way to make a third environment. i.e. Prod is `main`, "Development" is just a set of env vars for local development, and preview deployment is effectively *all branches that aren't main*.

When you try to set an env variable on a preview branch named `main` it doesn't work.

![image](https://user-images.githubusercontent.com/26855/206888404-267c8eb1-2bfe-4b07-b0c2-63bc18e3e516.png)

I'm OK with the analytics and stats to be separate for dev / prod. Besides, it doesn't cost us anything.

**Comment by dhmacs** [comment]
> When you try to set an env variable on a preview branch named main it doesn't work.

I'm confused, `main` is not a "preview" branch, so the error should be expected 🤔 

> Preview branches (as close to prod as is possible so QA is effective)

All PRs so far have been validated against preview branches on `react-commerce` as far as I can tell. 

Beside using `react-commerce-prod` to run the live site, are there other use cases that we're using `react-commerce-prod` for? 
I agree that's not a big deal to keep it as is for now, but it doesn't seem like we're using `react-commerce-prod` in our development or QA workflow either.

**Comment by danielbeardsley** [comment]
> I'm confused, `main` is not a "preview" branch, so the error should be expected

Precisely. I was demonstrating to Sterling that what he wants (an additional deployment with different environment variables, but also using `main`) isn't possible.

> Beside using react-commerce-prod to run the live site, are there other use cases that we're using react-commerce-prod for? I agree that's not a big deal to keep it as is for now, but it doesn't seem like we're using react-commerce-prod in our development or QA workflow either.

Heh, I was going to say the same about `react-commerce`. Not sure about folks doing QA, but I pretty much only use preview branches on `react-commerce-prod` for QA because I want to see exactly how the app with look and act when it's deployed.

Either way, we need two deployments of `main` with different env variables and this is the most straightforward way at the moment.

**Comment by dhmacs** [comment]
> Heh, I was going to say the same about react-commerce. Not sure about folks doing QA, but I pretty much only use preview branches on react-commerce-prod for QA because I want to see exactly how the app with look and act when it's deployed.

I think we're saying the same thing here. Only one project is needed for QA, regardless of whether it's `react-commerce` or `react-commerce-prod`. By checking latest PRs it seems to be `react-commerce`, that's the one I've been linking to in QA steps also, but I don't mind using `react-commerce-prod` from now on.

> Precisely. I was demonstrating to Sterling that what he wants (an additional deployment with different environment variables, but also using main) isn't possible.

It's still not clear to me, what's the use case for having two deployments for `main` branch? `react-commerce-prod` `main` is the live site. Is `react-commerce` `main` branch preview being used for some other purpose?

cc @danielbeardsley @sterlinghirsh

**Comment by danielbeardsley** [comment]
> Is `react-commerce` `main` branch preview being used for some other purpose?

Yes, it is what `www.cominor.com/Parts`  (and all other subdomains and paths point to). It's effectively how QAing the integration between our PHP app and react-commerce is done.
