### ISSUE TITLE
Fix prettier github check output

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#852]
On this PR, the prettier run failed with a ton of unrelated output, but didn't seem to mention the one file that did have an issue, which was a double-to-single quote change in frontend/templates/product/index.tsx. On my local machine, it worked fine. https://github.com/iFixit/react-commerce/pull/851 

Also, seems like this should show up in the post-commit hook / vscode.

**Comment by danielbeardsley** [comment]
I've been running into this too. Makes this check nearly useless and certainly time-wasting:
https://github.com/iFixit/react-commerce/actions/runs/3587624046/jobs/6038178485

**Comment by masonmcelvain** [comment]
The logs for both those pulls expired, so it's hard to tell what went wrong. I'm assuming this is the `format.yml` workflow, since `lint.yml` uses eslint not prettier.

I just tried opening a [pull](https://github.com/iFixit/react-commerce/pull/1490) that had misformatted code, and prettier correctly reformatted it with a new commit. So let's close until we see it happen again
