### ISSUE TITLE
Use value_propositions from metafield

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#910]
We added product metafield value_propositions, but we're still showing hardcoded values. Use the ones from the metafield.

**Comment by danielbeardsley** [comment]
I think for now, I'm going to just update the hard-coded values to meet the spec in the google sheet from:
https://github.com/iFixit/ifixit/issues/45298

Until we actually have data that differs per-product, I don't think it's worth putting it in a metafield.

**Comment by danielcliu-ifixit** [comment]
@danielbeardsley wait so are you picking up #45298? Otherwise ill pick it up

**Comment by danielbeardsley** [comment]
I've pushed this onto next sprint because the change has been made to the hard-coded values in react-commerce:
https://github.com/iFixit/react-commerce/pull/911

**Comment by danielbeardsley** [comment]
I've pushed this onto next sprint because the change has been made to the hard-coded values in react-commerce:
https://github.com/iFixit/react-commerce/pull/911

**Comment by sterlinghirsh** [comment]
This was closed mistakenly

**Comment by danielcliu-ifixit** [comment]
@sterlinghirsh is that because we should have opened a new issue for just changing the hard-coded values? Or is there something else we need done before launch?

**Comment by sterlinghirsh** [comment]
@danielcliu-ifixit Yeah Danny's issue said "closes" but should have been "connects". We may end up wanting to take another approach here anyway, though.

**Comment by danielbeardsley** [comment]
I'd argue that unless we have a good reason to diverge from the current system (keeping the value props in the repo and choosing which to display based on the product data), I vote we close this issue.

This issue as written doesn't need to be done and is actually a regression. I chose this direction (switching the value propositions in this app) because it seemed like it might be tricky to inject data (two variants of text and an icon) into a pre-structured set of value props and keeping 10000 copies of the data makes it harder to update them.

**Comment by sterlinghirsh** [comment]
OK we can always reopen it if we need to.
