### ISSUE TITLE
Match proposition icons

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#928]
### Overview:

There is a mismatch of proposition icons used in the sidebar section and larger section. The Purchase with purpose icons should be the same.

![after](https://user-images.githubusercontent.com/95656772/198400661-0818208b-c964-4225-af9b-de28b673cb70.png)

![section](https://user-images.githubusercontent.com/95656772/198400502-9b03bd71-14d7-4899-98c2-59390c7de50b.png)

---

I noticed that the faRocket, faShieldCheck, and faBadgeDollar icons are now _duotone_ instead of solid after https://github.com/iFixit/react-commerce/pull/911 was merged 

![197231093-5f52c780-e788-4e9e-b022-eb865690a5c3](https://user-images.githubusercontent.com/95656772/198400376-9177db89-97d3-45b3-a997-2e6f925e54b8.jpg)

This is because the List was moved into a return function BuyBoxPropositionSection() inside of **ServiceValuePropositionSection/index.tsx**, and this file uses _duotone_ for the icon imports

![duotone](https://user-images.githubusercontent.com/95656772/198400009-e6c540d9-af88-41d3-8e2b-f18166b10933.png)

![after](https://user-images.githubusercontent.com/95656772/198400327-75fa07df-fd64-486b-a0c8-fdac3b70719e.png)

I'm not 100% which design was intended, but I wanted to note that it has changed recently

CC: @federicobadini @dhmacs

**Comment by danielcliu-ifixit** [comment]
this icon switch is fixed in https://github.com/iFixit/react-commerce/pull/933

**Comment by erinemay** [comment]
And looking at the mockups, it looks like they were meant to be different. Since we're using the solid versions and the icons look different between the two value propositions, I'm gonna go ahead and close this. 
![image](https://user-images.githubusercontent.com/72166715/198417275-9e215643-626d-4441-b503-92d753eea3b9.png)
![image](https://user-images.githubusercontent.com/72166715/198417305-f5f1b8f1-a7de-4fa4-83a1-33c424e7a8c6.png)

Figma (text is obviously different): 
![image](https://user-images.githubusercontent.com/72166715/198417637-cd8e704a-ee4f-4094-aab5-d7b2f7dffaa1.png)
![image](https://user-images.githubusercontent.com/72166715/198417584-c525befb-10b6-46e9-95bd-7e5015d83c59.png)
