### ISSUE TITLE
Bug: Featured Product auto-scrolling is wonky

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#945]
When clicking on a Featured Product link, then clicking back, the browser zips down to the bottom of the page and then back up. It's a wild ride.

https://user-images.githubusercontent.com/7053450/198706800-cb0711f2-f96e-411a-bbef-41377be0e396.mp4

And in Firefox (not Chrome .. unsure of other browsers) clicking a Featured Product has unpredictable auto-scrolling results. 

https://user-images.githubusercontent.com/7053450/198706636-04f079b2-7770-41c8-896a-2481156c84e4.mp4

**Comment by federicobadini** [comment]
I've followed this issue since a very long time. Across the various Nextjs versions to which we upgraded this behaviour was little by little improved, but it is still far from being correct.
From my experience, Firefox is still problematic while the experience on chrome has improved.

There is an experimental flag [`scrollRestoration`](https://github.com/vercel/next.js/commit/38bd1a024cb25923d8ea15f269a7294d073684d8) that aimed at resolving the issue but again this is not always working correctly. 
Here is a [branch](https://react-commerce-prod-git-experiment-on-scroll-restoration-ifixit.vercel.app/products/iphone-11-screen) in which it is enabled and you can see how, depending on the browser you use, it behaves differently: sometimes it doesn't even try to restore the scroll position.

The good news is that the Nextjs team claim they have [resolved](https://github.com/vercel/next.js/issues/3303#issuecomment-1617910905) the issue in App router. 
I would just stick a bit more with what we have and see if we manage to progressively migrate to app router we could have this fixed for free
