### ISSUE TITLE
iFixit API: use `IFixitAPIClient` everywhere

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#949]
### Problem
We make quite a few requests with a bare `fetch()` call. This doesn't log to sentry and doesn't generate a log for the async operation

### Do This
Get an instance of the api client and use it:
```
const client = new IFixitAPIClient({origin: IFIXIT_ORIGIN});
```   

Or wrap it like we've done with the devices api if you want more type info or are going to be using this endpoint from more than one place:
https://github.com/iFixit/react-commerce/blob/2ca75fa98a9fd28a1698615ac949fd1e2b9313d0/frontend/lib/ifixit-api/devices.ts#L7-L21

**Comment by dhmacs** [comment]
I started working on this and I have an idea. Instead of having to remember to use `sentryFetch` everywhere, and disseminate Sentry dependencies throughout our codebase, why don't we intercept `globals.fetch` and `window.fetch` instead?

It'll look like this:

```ts
const originalFetch = window.fetch;

window.fetch = async (input, init) => {
  try {
    const response = await originalFetch(input, init);
    // Handle exceptions
    return response;
  } catch (error) {
    // Handle network error logging
    throw error;
  }
}
```

And pretty much the same thing for `globals.fetch`.

Thoughts?

cc @danielbeardsley @masonmcelvain

**Comment by dhmacs** [comment]
This would address also #948

**Comment by masonmcelvain** [comment]
So instead of explicitly capturing the exception on non-200 responses (current implementation shown below), we would throw and let Sentry implicitly record the exception (in contexts where we have Sentry set up, i.e. `frontend/`?

https://github.com/iFixit/react-commerce/blob/0ea458b75a33fa44cac8d816aef0204dad19b761/packages/sentry/index.tsx#L19-L31

That seems like it would work, and it would be very nice not to have to add Sentry as a dependency in so many of our packages.

**Comment by dhmacs** [comment]
No, the snippet that I wrote above is a general implementation for how you might intercept fetch and inject custom code. The custom code that will go in there  is the current `sentryFetch` implementation that you just referenced.

The only difference is that won't depend explicitly on `sentryFetch`, we would just use the standard `fetch` as we're used to and the sentry logging would be injected at runtime.

For example, instead of doing:

```ts
   const response = await sentryFetch(`${STRAPI_ORIGIN}/graphql`, {
      // etc etc
   });
```

we can just use `fetch` as we'd normally do:

```ts
   const response = await fetch(`${STRAPI_ORIGIN}/graphql`, {
      // etc etc
   });
```

You can think of this as a sort of middleware if you want.

Main advantages are:
- Don't need to remember to use `sentryFetch` instead of `fetch`
- The code does not depend on Sentry, so it would be easier to swap Sentry for something else or to extend the logging

**Comment by danielbeardsley** [comment]
I think that's an OK solution to ensuring we report failed requests to sentry. That said, it doesn't solve *this* problem (using the iFixit API client everywhere)

**Comment by dhmacs** [comment]
@danielbeardsley you're right, my mind kind of mixed the two issues together for some reason 😅 But I'm working on this one as well 👍
